"""Patch proposal service — propose/verify/approve/reject/sandbox-apply (v1.6)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy.orm import sessionmaker

from scientist_lab.domain.models import new_id
from scientist_lab.patching.approval_seal import (
    ApprovalSealError,
    attach_approval_seal,
    compare_approval_seal,
    invalidate_approval,
)
from scientist_lab.patching.context_bundle import (
    build_code_context_bundle,
    digits_improvement_patch_request,
)
from scientist_lab.patching.context_models import (
    CodeContextBundle,
    ContextSizeBudget,
    PatchRequest,
)
from scientist_lab.patching.context_store import (
    CodeContextRepository,
    export_code_context_bundle,
)
from scientist_lab.patching.fingerprint import fingerprint_diff
from scientist_lab.patching.evidence import (
    PatchMergeDecision,
    build_patch_evidence,
)
from scientist_lab.patching.models import PatchApproval, PatchProposal
from scientist_lab.patching.path_policy import PathPolicy
from scientist_lab.patching.real_patch_planner import (
    RealPatchPlanner,
    RealPatchPlannerError,
)
from scientist_lab.patching.real_mode import (
    DEFAULT_PATCH_PROVIDER_BUDGET,
    PatchBudgetStore,
    PatchProviderBudget,
    PatchRealModeError,
    PatchRealModePolicy,
    patch_provider_doctor,
)
from scientist_lab.patching.repository import PatchRepository
from scientist_lab.patching.sandbox_checks import (
    SandboxTestProfile,
    SandboxTestRunner,
)
from scientist_lab.patching.verifier import PatchVerifier
from scientist_lab.patching.workspace import PatchSandbox
from scientist_lab.storage.artifact_store import write_json


def build_mock_unified_diff(
    *,
    relative_path: str = (
        "experiment_apps/rgbt_detection_real/adapters/mock_patch_note.md"
    ),
) -> str:
    """Deterministic mock Unified Diff: new file inside the allow-list."""
    return (
        f"diff --git a/{relative_path} b/{relative_path}\n"
        "new file mode 100644\n"
        "--- /dev/null\n"
        f"+++ b/{relative_path}\n"
        "@@ -0,0 +1,4 @@\n"
        "+# Mock patch note\n"
        "+\n"
        "+Addresses missing controlled fusion ablation rationale.\n"
        "+Generated by MockProvider; apply only inside sandbox until human merge.\n"
    )


class PatchingService:
    """Lifecycle for restricted PatchProposal objects.

    Main workspace is never mutated. Sandbox apply writes only under
    ``sandbox_root/<patch_id>/``.
    """

    def __init__(
        self,
        session_factory: sessionmaker,
        *,
        project_root: Path | str | None = None,
        sandbox_root: Path | str | None = None,
        outputs_root: Path | str | None = None,
        policy: PathPolicy | None = None,
    ) -> None:
        self._repo = PatchRepository(session_factory)
        self._contexts = CodeContextRepository(session_factory)
        self.policy = policy or PathPolicy()
        self.context_policy = PathPolicy.for_code_context()
        self.verifier = PatchVerifier(self.policy)
        root = Path(project_root) if project_root else Path.cwd()
        self.project_root = root.resolve()
        self.sandbox_root = Path(
            sandbox_root
            if sandbox_root is not None
            else (self.project_root / "outputs" / "_patch_sandboxes")
        )
        self.outputs_root = Path(
            outputs_root
            if outputs_root is not None
            else (self.project_root / "outputs")
        )
        self.sandbox = PatchSandbox(
            project_root=self.project_root,
            sandbox_root=self.sandbox_root,
            policy=self.context_policy,
        )
        self.sandbox_tests = SandboxTestRunner(policy=self.context_policy)
        self.real_mode = PatchRealModePolicy()
        self.budget_store = PatchBudgetStore(
            self.outputs_root / "_patch_budgets"
        )

    def build_code_context(
        self,
        request: PatchRequest | None = None,
        *,
        persist: bool = True,
        budget: ContextSizeBudget | None = None,
        bundle_id: str | None = None,
        digits_demo: bool = False,
    ) -> dict[str, Any]:
        """Build a restricted CodeContextBundle (v2.2.1; no provider call)."""
        req = request
        if req is None:
            if not digits_demo:
                raise ValueError("PatchRequest required unless digits_demo=True")
            req = digits_improvement_patch_request()
        bundle = build_code_context_bundle(
            req,
            project_root=self.project_root,
            policy=self.context_policy,
            budget=budget,
            bundle_id=bundle_id,
        )
        if persist:
            self._contexts.upsert(bundle)
        return {
            "bundle": bundle.model_dump(mode="json"),
            "persisted": persist,
            "provider_call": False,
        }

    def show_code_context(self, bundle_id: str) -> dict[str, Any]:
        bundle = self._contexts.require(bundle_id)
        return {"bundle": bundle.model_dump(mode="json")}

    def export_code_context(
        self,
        bundle_id: str,
        *,
        output_path: Path | str | None = None,
    ) -> dict[str, Any]:
        bundle = self._contexts.require(bundle_id)
        out = (
            Path(output_path)
            if output_path
            else (
                self.outputs_root
                / "_code_contexts"
                / f"{bundle.bundle_id}_{bundle.context_sha256[:12]}.json"
            )
        )
        meta = export_code_context_bundle(bundle, output_path=out)
        return {"export": meta, "bundle_id": bundle.bundle_id}

    def list_code_contexts(
        self, project_id: str, *, limit: int = 50
    ) -> list[CodeContextBundle]:
        return self._contexts.list_for_project(project_id, limit=limit)

    def propose_mock(
        self,
        project_id: str,
        *,
        title: str | None = None,
        rationale: str | None = None,
        evidence_gap_ids: list[str] | None = None,
        unified_diff: str | None = None,
        auto_verify: bool = True,
    ) -> dict[str, Any]:
        diff = unified_diff or build_mock_unified_diff()
        fp = fingerprint_diff(diff)
        duplicate = self._repo.find_by_fingerprint(fp)
        proposal = PatchProposal(
            patch_id=new_id("patch"),
            project_id=project_id,
            status="proposed",
            title=title
            or "Mock patch: document fusion ablation evidence gap",
            rationale=rationale
            or (
                "MockProvider proposes a documentation-level change addressing "
                "a missing controlled fusion ablation evidence gap."
            ),
            evidence_gap_ids=list(
                evidence_gap_ids
                or ["missing controlled fusion ablation"]
            ),
            unified_diff=diff,
            fingerprint_sha256=fp,
            provider="mock",
            metadata={
                "applied_main": False,
                "applied_sandbox": False,
                "apply_main_available": False,
            },
        )
        if auto_verify:
            verification = self.verifier.verify(
                diff,
                duplicate_of=duplicate.patch_id if duplicate else None,
            )
            proposal.verification = verification
            proposal.files_touched = list(verification.files_touched)
            proposal.fingerprint_sha256 = verification.fingerprint_sha256
            proposal.status = (
                "verified" if verification.ok else "rejected_by_verifier"
            )
        self._repo.upsert(proposal)
        return self._view(proposal)

    def propose_real(
        self,
        bundle_id: str | CodeContextBundle,
        *,
        provider: Any | None = None,
        requested_provider: str = "openai-compatible",
        allow_network: bool = False,
        transport: Any | None = None,
        openai_config: Any | None = None,
        real_only: bool = True,
        auto_verify: bool = True,
        environ: dict[str, str] | None = None,
        budget: PatchProviderBudget | None = None,
        apply_project_budget: bool = True,
    ) -> dict[str, Any]:
        """Build PatchProposal from CodeContextBundle via real provider (v2.2.2/4).

        Never silently falls back to ``propose_mock`` when ``real_only=True``.
        Offline tests may pass ``transport=MockTransport`` with ``allow_network=False``.
        v2.2.4 wraps the provider with call/token/cost budget limits.
        """
        from scientist_lab.agents.provider_bridge import load_openai_config_for_runtime
        from scientist_lab.llm.factory import create_llm_provider
        from scientist_lab.llm.limits import ProviderLimitExceeded

        if isinstance(bundle_id, CodeContextBundle):
            bundle = bundle_id
        else:
            bundle = self._contexts.require(str(bundle_id))

        requested = self.real_mode.assert_mode(
            requested_provider=requested_provider,
            real_only=real_only,
            allow_network=bool(allow_network),
            transport=transport,
            provider=provider,
        )

        caps = budget or self.real_mode.budget()
        session_caps = caps
        if apply_project_budget:
            status = self.budget_store.status(bundle.project_id, budget=caps)
            if status["exhausted"]:
                raise PatchRealModeError(
                    f"patch provider budget exhausted for project "
                    f"{bundle.project_id}: {status['used']}"
                )
            rem = status["remaining"]
            session_caps = PatchProviderBudget(
                max_calls=max(1, int(rem["calls"])),
                max_total_tokens=max(1, int(rem["total_tokens"])),
                max_cost_usd=max(0.0001, float(rem["cost_usd"])),
                max_latency_ms=caps.max_latency_ms,
            )

        llm = provider
        if llm is None:
            cfg = openai_config
            if cfg is None and (allow_network or transport is not None):
                cfg = load_openai_config_for_runtime(
                    allow_network=bool(allow_network),
                    environ=environ,
                    openai_config=None,
                )
            try:
                llm = create_llm_provider(
                    requested,
                    allow_network=bool(allow_network),
                    environ=environ,
                    openai_config=cfg,
                    transport=transport,
                )
            except Exception as exc:  # noqa: BLE001
                raise RealPatchPlannerError(
                    f"cannot construct real patch provider: {exc}"
                ) from exc

        llm, ledger, applied_budget = self.real_mode.wrap_with_budget(
            llm, budget=session_caps
        )

        planner = RealPatchPlanner(
            llm,
            requested_provider=requested,
            real_only=real_only,
            policy=self.context_policy,
        )
        try:
            proposal, audit = planner.propose(bundle, auto_verify=False)
        except ProviderLimitExceeded as exc:
            raise PatchRealModeError(f"patch provider budget exceeded: {exc}") from exc
        except Exception:
            # Explicit: do NOT call propose_mock here.
            raise

        project_usage = None
        if apply_project_budget and ledger.call_count > 0:
            project_usage = self.budget_store.add_usage(bundle.project_id, ledger)

        if auto_verify:
            context_verifier = PatchVerifier(self.context_policy)
            found = self._repo.find_by_fingerprint(
                proposal.fingerprint_sha256, exclude_patch_id=proposal.patch_id
            )
            duplicate_id = found.patch_id if found else None
            if duplicate_id:
                proposal.metadata["duplicate_of"] = duplicate_id
            verification = context_verifier.verify(
                proposal.unified_diff, duplicate_of=duplicate_id
            )
            proposal.verification = verification
            proposal.files_touched = list(verification.files_touched)
            proposal.fingerprint_sha256 = verification.fingerprint_sha256
            proposal.status = (
                "verified" if verification.ok else "rejected_by_verifier"
            )
            audit["verification_ok"] = verification.ok

        proposal.metadata["provider_budget"] = applied_budget.model_dump()
        proposal.metadata["provider_usage"] = ledger.as_dict()
        proposal.metadata["force_real_only"] = True

        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["provider_audit"] = audit
        view["fallback_used"] = False
        view["bundle_id"] = bundle.bundle_id
        view["context_sha256"] = bundle.context_sha256
        view["provider_budget"] = applied_budget.model_dump()
        view["provider_usage"] = ledger.as_dict()
        if project_usage is not None:
            view["project_provider_usage"] = project_usage
        return view

    def show_patch_budget(
        self,
        project_id: str,
        *,
        budget: PatchProviderBudget | None = None,
    ) -> dict[str, Any]:
        return self.budget_store.status(project_id, budget=budget)

    def patch_provider_doctor(
        self,
        *,
        requested_provider: str = "openai-compatible",
        allow_network: bool = False,
        environ: dict[str, str] | None = None,
        transport_injected: bool = False,
    ) -> dict[str, Any]:
        import os

        env = environ if environ is not None else dict(os.environ)
        return patch_provider_doctor(
            requested_provider=requested_provider,
            allow_network=bool(allow_network),
            has_api_key=bool(str(env.get("LLM_API_KEY") or "").strip()),
            has_base_url=bool(str(env.get("LLM_BASE_URL") or "").strip()),
            has_model=bool(str(env.get("LLM_MODEL") or "").strip()),
            transport_injected=transport_injected,
        )

    def show(self, patch_id: str) -> dict[str, Any]:
        return self._view(self._repo.require(patch_id))

    def verify(self, patch_id: str) -> dict[str, Any]:
        proposal = self._repo.require(patch_id)
        duplicate = self._repo.find_by_fingerprint(
            fingerprint_diff(proposal.unified_diff),
            exclude_patch_id=proposal.patch_id,
        )
        verification = self.verifier.verify(
            proposal.unified_diff,
            duplicate_of=duplicate.patch_id if duplicate else None,
        )
        proposal.verification = verification
        proposal.files_touched = list(verification.files_touched)
        proposal.fingerprint_sha256 = verification.fingerprint_sha256
        if proposal.status not in {
            "approved",
            "rejected",
            "merged",
            "discarded",
            "applied_sandbox",
            "failed_sandbox",
        }:
            proposal.status = (
                "verified" if verification.ok else "rejected_by_verifier"
            )
        self._repo.upsert(proposal)
        return self._view(proposal)

    def approve(self, patch_id: str, *, reason: str = "") -> dict[str, Any]:
        proposal = self._repo.require(patch_id)
        if proposal.status == "rejected_by_verifier":
            raise ValueError("cannot approve a patch rejected by verifier")
        if proposal.status == "rejected":
            raise ValueError("cannot approve a human-rejected patch")
        if proposal.verification is None or not proposal.verification.ok:
            self.verify(patch_id)
            proposal = self._repo.require(patch_id)
            if proposal.verification is None or not proposal.verification.ok:
                raise ValueError("patch must pass verification before approval")
        # Ensure patch fingerprint is current before sealing.
        proposal.fingerprint_sha256 = (
            proposal.fingerprint_sha256
            or fingerprint_diff(proposal.unified_diff)
        )
        proposal.approval = attach_approval_seal(
            proposal,
            decision="approved",
            reason=reason or "human approved for sandbox apply",
            decided_by="human",
        )
        proposal.status = "approved"
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "applied_main": False,
            "apply_main_available": False,
            "sandbox_apply_available": True,
            "approval_invalidated": False,
        }
        self._repo.upsert(proposal)
        return self._view(proposal)

    def reject(self, patch_id: str, *, reason: str = "") -> dict[str, Any]:
        proposal = self._repo.require(patch_id)
        proposal.approval = attach_approval_seal(
            proposal,
            decision="rejected",
            reason=reason or "human rejected",
            decided_by="human",
        )
        proposal.status = "rejected"
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "applied_main": False,
            "applied_sandbox": False,
            "apply_main_available": False,
            "sandbox_apply_available": False,
        }
        self._repo.upsert(proposal)
        return self._view(proposal)

    def check_approval_seal(self, patch_id: str, *, persist: bool = True) -> dict[str, Any]:
        """Validate approval fingerprints against current proposal content."""
        proposal = self._repo.require(patch_id)
        report = compare_approval_seal(proposal)
        if proposal.status == "approved" and not report["ok"]:
            proposal = invalidate_approval(
                proposal, reason=str(report.get("message") or "seal mismatch")
            )
            if persist:
                self._repo.upsert(proposal)
        view = self._view(proposal)
        view["seal_report"] = report
        return view

    def apply_sandbox(
        self, patch_id: str, *, force: bool = False
    ) -> dict[str, Any]:
        """Apply an approved patch into an isolated sandbox directory only."""
        proposal = self._repo.require(patch_id)
        if proposal.status not in {"approved", "failed_sandbox"}:
            raise ValueError(
                f"sandbox apply requires approved (or retry failed_sandbox) "
                f"status; got {proposal.status!r}"
            )
        if proposal.verification is None or not proposal.verification.ok:
            raise ValueError("patch verification must be ok before sandbox apply")

        # v2.2.5: refuse sandbox apply if sealed content was tampered with.
        if (
            proposal.approval is not None
            and proposal.approval.decision == "approved"
            and not proposal.approval.invalidated
        ):
            seal_report = compare_approval_seal(proposal)
            if not seal_report["ok"]:
                proposal = invalidate_approval(
                    proposal,
                    reason=str(seal_report.get("message") or "seal mismatch"),
                )
                self._repo.upsert(proposal)
                raise ApprovalSealError(
                    "approval invalidated — content changed after approval; "
                    f"re-approve required ({seal_report.get('message')})"
                )

        result = self.sandbox.apply(
            proposal.patch_id,
            proposal.unified_diff,
            metadata={
                "project_id": proposal.project_id,
                "fingerprint_sha256": proposal.fingerprint_sha256,
            },
            force=force or proposal.status == "failed_sandbox",
        )
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "applied_main": False,
            "apply_main_available": False,
            "applied_sandbox": bool(result.ok),
            "sandbox_dir": result.sandbox_dir,
            "sandbox_files_written": list(result.files_written),
            "sandbox_manifest": result.manifest_path,
            "sandbox_error": result.error,
        }
        proposal.status = "applied_sandbox" if result.ok else "failed_sandbox"
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["sandbox"] = {
            "ok": result.ok,
            "sandbox_dir": result.sandbox_dir,
            "files_written": result.files_written,
            "error": result.error,
            "manifest_path": result.manifest_path,
            "main_workspace_modified": False,
            "policy": "for_code_context",
        }
        return view

    def list_sandbox_test_profiles(self) -> dict[str, Any]:
        from scientist_lab.patching.sandbox_registry import list_sandbox_test_profiles

        items = list_sandbox_test_profiles()
        return {
            "items": items,
            "total": len(items),
            "runs_shell": False,
            "arbitrary_commands_forbidden": True,
        }

    def test_sandbox(
        self,
        patch_id: str,
        *,
        profile: SandboxTestProfile = "smoke",
    ) -> dict[str, Any]:
        """Run allow-listed in-process checks against an applied sandbox."""
        proposal = self._repo.require(patch_id)
        if proposal.status != "applied_sandbox":
            raise ValueError(
                f"sandbox tests require status applied_sandbox; "
                f"got {proposal.status!r}"
            )
        meta = dict(proposal.metadata or {})
        sandbox_dir = meta.get("sandbox_dir")
        if not sandbox_dir:
            raise ValueError("patch metadata missing sandbox_dir")
        files_written = list(meta.get("sandbox_files_written") or [])
        report = self.sandbox_tests.run(
            patch_id=proposal.patch_id,
            sandbox_dir=sandbox_dir,
            files_written=files_written,
            profile=profile,
        )
        proposal.metadata = {
            **meta,
            "sandbox_tests": report.to_dict(),
            "sandbox_tests_ok": report.ok,
            "sandbox_test_profile": profile,
        }
        # Status stays applied_sandbox; evidence recording is v1.6.6.
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["sandbox_tests"] = report.to_dict()
        return view

    def record_evidence(
        self,
        patch_id: str,
        *,
        require_tests: bool = False,
        build_feedback: bool = True,
    ) -> dict[str, Any]:
        """Persist PatchEvidence from an applied (and preferably tested) sandbox."""
        from scientist_lab.patching.feedback import build_patch_feedback_package

        proposal = self._repo.require(patch_id)
        if proposal.status not in {"applied_sandbox", "evidence_recorded"}:
            raise ValueError(
                f"record_evidence requires applied_sandbox; got {proposal.status!r}"
            )
        meta = dict(proposal.metadata or {})
        if require_tests and meta.get("sandbox_tests") is None:
            raise ValueError(
                "sandbox tests required before recording evidence "
                "(run patch-test-sandbox first, or omit --require-tests)"
            )
        evidence = build_patch_evidence(proposal, outputs_root=self.outputs_root)
        feedback: dict[str, Any] | None = None
        if build_feedback:
            feedback = build_patch_feedback_package(
                evidence, proposal, outputs_root=self.outputs_root
            )
            evidence.feedback_package_path = str(feedback.get("artifact_path") or "")
            # Rewrite artifact with feedback path.
            if evidence.artifact_path:
                write_json(
                    Path(evidence.artifact_path),
                    evidence.model_dump(mode="json"),
                )
        proposal.metadata = {
            **meta,
            "patch_evidence": evidence.model_dump(mode="json"),
            "patch_evidence_id": evidence.evidence_id,
            "patch_feedback": feedback,
            "patch_verdict": evidence.verdict,
            "applied_main": False,
            "apply_main_available": False,
        }
        proposal.status = "evidence_recorded"
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["patch_evidence"] = evidence.model_dump(mode="json")
        if feedback is not None:
            view["patch_feedback"] = feedback
        return view

    def export_patch_replay(
        self,
        patch_id: str,
        *,
        output_dir: Path | str,
        provider_response: dict[str, Any] | None = None,
        label: str = "patch_replay",
    ) -> dict[str, Any]:
        """Export a redacted Patch Replay Bundle for offline CI (v2.2.8)."""
        from scientist_lab.patching.replay_bundle import build_patch_replay_bundle

        proposal = self._repo.require(patch_id)
        meta = dict(proposal.metadata or {})
        context_payload = None
        bundle_id = meta.get("bundle_id")
        if bundle_id:
            ctx = self._contexts.get(str(bundle_id))
            if ctx is not None:
                context_payload = ctx.model_dump(mode="json")
        if context_payload is None:
            context_payload = {
                "bundle_id": bundle_id or "",
                "request_id": meta.get("request_id") or "",
                "project_id": proposal.project_id,
                "source_commit": meta.get("source_commit") or "",
                "context_sha256": meta.get("context_sha256") or "",
                "goal": proposal.title,
                "snapshots": [],
                "metadata": {"provider_call": True, "exported_from_patch": True},
            }

        response = provider_response or {
            "title": proposal.title,
            "rationale": proposal.rationale,
            "unified_diff": proposal.unified_diff,
            "risks": list(meta.get("risks") or []),
            "expected_tests": list(meta.get("expected_tests") or []),
            "evidence_gap_ids": list(proposal.evidence_gap_ids or []),
        }
        verification = (
            proposal.verification.model_dump(mode="json")
            if proposal.verification is not None
            else None
        )
        return build_patch_replay_bundle(
            output_dir=output_dir,
            bundle=context_payload,
            provider_response=response,
            proposal=proposal.model_dump(mode="json"),
            verification=verification,
            feedback=meta.get("patch_feedback"),
            provider_audit={
                "requested_provider": "openai-compatible",
                "actual_provider": proposal.provider,
                "fallback_used": False,
            },
            label=label,
        )

    def replay_patch_from_bundle(
        self,
        bundle_dir: Path | str,
        *,
        persist_context: bool = True,
        auto_verify: bool = True,
    ) -> dict[str, Any]:
        """Replay a recorded provider response via MockTransport (zero network)."""
        import json as _json

        from pydantic import SecretStr

        from scientist_lab.llm.http_transport import HttpResponse, MockTransport
        from scientist_lab.llm.openai_config import OpenAICompatibleConfig
        from scientist_lab.patching.context_models import CodeContextBundle
        from scientist_lab.patching.replay_bundle import (
            load_patch_replay_bundle,
            replay_patch_static_checks,
        )
        from scientist_lab.patching.real_mode import PatchProviderBudget

        loaded = load_patch_replay_bundle(bundle_dir)
        static = replay_patch_static_checks(bundle_dir, policy=self.context_policy)
        if not static["ok"]:
            raise ValueError(
                "static replay checks failed: "
                + _json.dumps(static.get("verification"), ensure_ascii=False)
            )

        context_payload = loaded.get("code_context_bundle") or {}
        context = CodeContextBundle.model_validate(context_payload)
        if persist_context:
            self._contexts.upsert(context)

        response_body = {
            "id": "chatcmpl-patch-replay",
            "choices": [
                {
                    "message": {
                        "role": "assistant",
                        "content": _json.dumps(
                            loaded.get("provider_response") or {},
                            ensure_ascii=False,
                        ),
                    }
                }
            ],
            "usage": {
                "prompt_tokens": 10,
                "completion_tokens": 20,
                "total_tokens": 30,
            },
        }
        transport = MockTransport(
            default_response=HttpResponse(
                status_code=200, body=_json.dumps(response_body)
            )
        )
        cfg = OpenAICompatibleConfig(
            base_url="https://replay.local/v1",
            api_key=SecretStr("sk-replay-offline-not-a-real-key"),
            model="replay-patch",
            allow_network=False,
            api_mode="chat_completions",
        )
        view = self.propose_real(
            context,
            openai_config=cfg,
            transport=transport,
            allow_network=False,
            real_only=True,
            auto_verify=auto_verify,
            budget=PatchProviderBudget(max_calls=2, max_total_tokens=20_000),
            apply_project_budget=False,
        )
        view["replay"] = {
            "bundle_dir": loaded["bundle_dir"],
            "static_checks": static,
            "network_used": False,
            "fallback_used": False,
            "secrets_redacted": True,
        }
        return view

    def decide_merge(
        self,
        patch_id: str,
        *,
        decision: str,
        reason: str = "",
    ) -> dict[str, Any]:
        """Record human merge/discard intent without touching the main tree."""
        proposal = self._repo.require(patch_id)
        if proposal.status not in {"evidence_recorded", "merged", "discarded"}:
            raise ValueError(
                f"merge decision requires evidence_recorded; got {proposal.status!r}"
            )
        if decision not in {"merge", "discard"}:
            raise ValueError("decision must be 'merge' or 'discard'")
        if proposal.status in {"merged", "discarded"}:
            expected = "merged" if decision == "merge" else "discarded"
            if proposal.status != expected:
                raise ValueError(
                    f"patch already decided as {proposal.status!r}; "
                    "cannot change decision in v1.6"
                )
            view = self._view(proposal)
            view["merge_decision"] = (proposal.metadata or {}).get("merge_decision")
            view["warning"] = (
                "Merge decision already recorded; main workspace was not modified."
            )
            return view

        now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        merge = PatchMergeDecision(
            decision=decision,  # type: ignore[arg-type]
            reason=reason
            or (
                "human approved merge intent (main tree not modified)"
                if decision == "merge"
                else "human discarded patch"
            ),
            decided_at=now,
            decided_by="human",
            applied_main=False,
        )
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "merge_decision": merge.model_dump(mode="json"),
            "applied_main": False,
            "apply_main_available": False,
        }
        proposal.status = "merged" if decision == "merge" else "discarded"
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["merge_decision"] = merge.model_dump(mode="json")
        view["warning"] = (
            "Merge decision recorded only; main workspace was not modified."
        )
        return view

    def list_patches(self, project_id: str) -> list[dict[str, Any]]:
        return [self._view(item) for item in self._repo.list_for_project(project_id)]

    def list_patches_all(
        self, *, project_id: str | None = None, limit: int = 100
    ) -> list[dict[str, Any]]:
        if project_id:
            items = self._repo.list_for_project(project_id)
            return [self._view(item) for item in items[: max(1, int(limit))]]
        return [self._view(item) for item in self._repo.list_all(limit=limit)]

    def _view(self, proposal: PatchProposal) -> dict[str, Any]:
        data = proposal.model_dump(mode="json")
        meta = dict(proposal.metadata or {})
        data["can_apply_main"] = False
        data["applied_main"] = bool(meta.get("applied_main"))
        seal_ok = True
        if (
            proposal.approval is not None
            and proposal.approval.decision == "approved"
            and proposal.status in {"approved", "failed_sandbox"}
        ):
            if proposal.approval.invalidated:
                seal_ok = False
            elif proposal.approval.content_seal is not None:
                seal_ok = bool(compare_approval_seal(proposal).get("ok"))
        data["can_apply_sandbox"] = (
            proposal.status in {"approved", "failed_sandbox"} and seal_ok
        )
        data["approval_seal_ok"] = seal_ok
        data["applied_sandbox"] = bool(meta.get("applied_sandbox"))
        data["can_test_sandbox"] = proposal.status == "applied_sandbox"
        data["sandbox_tests_ok"] = meta.get("sandbox_tests_ok")
        data["can_record_evidence"] = proposal.status in {
            "applied_sandbox",
            "evidence_recorded",
        }
        data["can_decide_merge"] = proposal.status == "evidence_recorded"
        data["patch_evidence_id"] = meta.get("patch_evidence_id")
        data["merge_decision"] = meta.get("merge_decision")
        # Back-compat keys used by v1.6.1–1.6.3 tests/CLI.
        data["can_apply"] = False
        data["applied"] = bool(meta.get("applied_sandbox"))
        return data
