"""Patch proposal service — propose/verify/approve/reject/sandbox-apply (v1.6)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy.orm import sessionmaker

from scientist_lab.domain.models import new_id
from scientist_lab.patching.fingerprint import fingerprint_diff
from scientist_lab.patching.evidence import (
    PatchMergeDecision,
    build_patch_evidence,
)
from scientist_lab.patching.models import PatchApproval, PatchProposal
from scientist_lab.patching.path_policy import PathPolicy
from scientist_lab.patching.repository import PatchRepository
from scientist_lab.patching.sandbox_checks import (
    SandboxTestProfile,
    SandboxTestRunner,
)
from scientist_lab.patching.verifier import PatchVerifier
from scientist_lab.patching.workspace import PatchSandbox


def build_mock_unified_diff(
    *,
    relative_path: str = (
        "experiment_apps/rgbt_detection_real/adapters/mock_patch_note.md"
    ),
) -> str:
    """Deterministic mock Unified Diff: new file inside the allow-list."""
    return (
        f"diff --git a/{relative_path} b/{relative_path}\n"
        "new file mode 100644\n"
        "--- /dev/null\n"
        f"+++ b/{relative_path}\n"
        "@@ -0,0 +1,4 @@\n"
        "+# Mock patch note\n"
        "+\n"
        "+Addresses missing controlled fusion ablation rationale.\n"
        "+Generated by MockProvider; apply only inside sandbox until human merge.\n"
    )


class PatchingService:
    """Lifecycle for restricted PatchProposal objects.

    Main workspace is never mutated. Sandbox apply writes only under
    ``sandbox_root/<patch_id>/``.
    """

    def __init__(
        self,
        session_factory: sessionmaker,
        *,
        project_root: Path | str | None = None,
        sandbox_root: Path | str | None = None,
        outputs_root: Path | str | None = None,
        policy: PathPolicy | None = None,
    ) -> None:
        self._repo = PatchRepository(session_factory)
        self.policy = policy or PathPolicy()
        self.verifier = PatchVerifier(self.policy)
        root = Path(project_root) if project_root else Path.cwd()
        self.project_root = root.resolve()
        self.sandbox_root = Path(
            sandbox_root
            if sandbox_root is not None
            else (self.project_root / "outputs" / "_patch_sandboxes")
        )
        self.outputs_root = Path(
            outputs_root
            if outputs_root is not None
            else (self.project_root / "outputs")
        )
        self.sandbox = PatchSandbox(
            project_root=self.project_root,
            sandbox_root=self.sandbox_root,
            policy=self.policy,
        )
        self.sandbox_tests = SandboxTestRunner(policy=self.policy)

    def propose_mock(
        self,
        project_id: str,
        *,
        title: str | None = None,
        rationale: str | None = None,
        evidence_gap_ids: list[str] | None = None,
        unified_diff: str | None = None,
        auto_verify: bool = True,
    ) -> dict[str, Any]:
        diff = unified_diff or build_mock_unified_diff()
        fp = fingerprint_diff(diff)
        duplicate = self._repo.find_by_fingerprint(fp)
        proposal = PatchProposal(
            patch_id=new_id("patch"),
            project_id=project_id,
            status="proposed",
            title=title
            or "Mock patch: document fusion ablation evidence gap",
            rationale=rationale
            or (
                "MockProvider proposes a documentation-level change addressing "
                "a missing controlled fusion ablation evidence gap."
            ),
            evidence_gap_ids=list(
                evidence_gap_ids
                or ["missing controlled fusion ablation"]
            ),
            unified_diff=diff,
            fingerprint_sha256=fp,
            provider="mock",
            metadata={
                "applied_main": False,
                "applied_sandbox": False,
                "apply_main_available": False,
            },
        )
        if auto_verify:
            verification = self.verifier.verify(
                diff,
                duplicate_of=duplicate.patch_id if duplicate else None,
            )
            proposal.verification = verification
            proposal.files_touched = list(verification.files_touched)
            proposal.fingerprint_sha256 = verification.fingerprint_sha256
            proposal.status = (
                "verified" if verification.ok else "rejected_by_verifier"
            )
        self._repo.upsert(proposal)
        return self._view(proposal)

    def show(self, patch_id: str) -> dict[str, Any]:
        return self._view(self._repo.require(patch_id))

    def verify(self, patch_id: str) -> dict[str, Any]:
        proposal = self._repo.require(patch_id)
        duplicate = self._repo.find_by_fingerprint(
            fingerprint_diff(proposal.unified_diff),
            exclude_patch_id=proposal.patch_id,
        )
        verification = self.verifier.verify(
            proposal.unified_diff,
            duplicate_of=duplicate.patch_id if duplicate else None,
        )
        proposal.verification = verification
        proposal.files_touched = list(verification.files_touched)
        proposal.fingerprint_sha256 = verification.fingerprint_sha256
        if proposal.status not in {
            "approved",
            "rejected",
            "merged",
            "discarded",
            "applied_sandbox",
            "failed_sandbox",
        }:
            proposal.status = (
                "verified" if verification.ok else "rejected_by_verifier"
            )
        self._repo.upsert(proposal)
        return self._view(proposal)

    def approve(self, patch_id: str, *, reason: str = "") -> dict[str, Any]:
        proposal = self._repo.require(patch_id)
        if proposal.status == "rejected_by_verifier":
            raise ValueError("cannot approve a patch rejected by verifier")
        if proposal.status == "rejected":
            raise ValueError("cannot approve a human-rejected patch")
        if proposal.verification is None or not proposal.verification.ok:
            self.verify(patch_id)
            proposal = self._repo.require(patch_id)
            if proposal.verification is None or not proposal.verification.ok:
                raise ValueError("patch must pass verification before approval")
        now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        proposal.approval = PatchApproval(
            decision="approved",
            reason=reason or "human approved for sandbox apply",
            decided_at=now,
            decided_by="human",
        )
        proposal.status = "approved"
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "applied_main": False,
            "apply_main_available": False,
            "sandbox_apply_available": True,
        }
        self._repo.upsert(proposal)
        return self._view(proposal)

    def reject(self, patch_id: str, *, reason: str = "") -> dict[str, Any]:
        proposal = self._repo.require(patch_id)
        now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        proposal.approval = PatchApproval(
            decision="rejected",
            reason=reason or "human rejected",
            decided_at=now,
            decided_by="human",
        )
        proposal.status = "rejected"
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "applied_main": False,
            "applied_sandbox": False,
            "apply_main_available": False,
            "sandbox_apply_available": False,
        }
        self._repo.upsert(proposal)
        return self._view(proposal)

    def apply_sandbox(
        self, patch_id: str, *, force: bool = False
    ) -> dict[str, Any]:
        """Apply an approved patch into an isolated sandbox directory only."""
        proposal = self._repo.require(patch_id)
        if proposal.status not in {"approved", "failed_sandbox"}:
            raise ValueError(
                f"sandbox apply requires approved (or retry failed_sandbox) "
                f"status; got {proposal.status!r}"
            )
        if proposal.verification is None or not proposal.verification.ok:
            raise ValueError("patch verification must be ok before sandbox apply")

        result = self.sandbox.apply(
            proposal.patch_id,
            proposal.unified_diff,
            metadata={
                "project_id": proposal.project_id,
                "fingerprint_sha256": proposal.fingerprint_sha256,
            },
            force=force or proposal.status == "failed_sandbox",
        )
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "applied_main": False,
            "apply_main_available": False,
            "applied_sandbox": bool(result.ok),
            "sandbox_dir": result.sandbox_dir,
            "sandbox_files_written": list(result.files_written),
            "sandbox_manifest": result.manifest_path,
            "sandbox_error": result.error,
        }
        proposal.status = "applied_sandbox" if result.ok else "failed_sandbox"
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["sandbox"] = {
            "ok": result.ok,
            "sandbox_dir": result.sandbox_dir,
            "files_written": result.files_written,
            "error": result.error,
            "manifest_path": result.manifest_path,
            "main_workspace_modified": False,
        }
        return view

    def test_sandbox(
        self,
        patch_id: str,
        *,
        profile: SandboxTestProfile = "smoke",
    ) -> dict[str, Any]:
        """Run allow-listed in-process checks against an applied sandbox."""
        proposal = self._repo.require(patch_id)
        if proposal.status != "applied_sandbox":
            raise ValueError(
                f"sandbox tests require status applied_sandbox; "
                f"got {proposal.status!r}"
            )
        meta = dict(proposal.metadata or {})
        sandbox_dir = meta.get("sandbox_dir")
        if not sandbox_dir:
            raise ValueError("patch metadata missing sandbox_dir")
        files_written = list(meta.get("sandbox_files_written") or [])
        report = self.sandbox_tests.run(
            patch_id=proposal.patch_id,
            sandbox_dir=sandbox_dir,
            files_written=files_written,
            profile=profile,
        )
        proposal.metadata = {
            **meta,
            "sandbox_tests": report.to_dict(),
            "sandbox_tests_ok": report.ok,
            "sandbox_test_profile": profile,
        }
        # Status stays applied_sandbox; evidence recording is v1.6.6.
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["sandbox_tests"] = report.to_dict()
        return view

    def record_evidence(
        self,
        patch_id: str,
        *,
        require_tests: bool = False,
    ) -> dict[str, Any]:
        """Persist PatchEvidence from an applied (and preferably tested) sandbox."""
        proposal = self._repo.require(patch_id)
        if proposal.status not in {"applied_sandbox", "evidence_recorded"}:
            raise ValueError(
                f"record_evidence requires applied_sandbox; got {proposal.status!r}"
            )
        meta = dict(proposal.metadata or {})
        if require_tests and meta.get("sandbox_tests") is None:
            raise ValueError(
                "sandbox tests required before recording evidence "
                "(run patch-test-sandbox first, or omit --require-tests)"
            )
        evidence = build_patch_evidence(proposal, outputs_root=self.outputs_root)
        proposal.metadata = {
            **meta,
            "patch_evidence": evidence.model_dump(mode="json"),
            "patch_evidence_id": evidence.evidence_id,
            "applied_main": False,
            "apply_main_available": False,
        }
        proposal.status = "evidence_recorded"
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["patch_evidence"] = evidence.model_dump(mode="json")
        return view

    def decide_merge(
        self,
        patch_id: str,
        *,
        decision: str,
        reason: str = "",
    ) -> dict[str, Any]:
        """Record human merge/discard intent without touching the main tree."""
        proposal = self._repo.require(patch_id)
        if proposal.status not in {"evidence_recorded", "merged", "discarded"}:
            raise ValueError(
                f"merge decision requires evidence_recorded; got {proposal.status!r}"
            )
        if decision not in {"merge", "discard"}:
            raise ValueError("decision must be 'merge' or 'discard'")
        if proposal.status in {"merged", "discarded"}:
            expected = "merged" if decision == "merge" else "discarded"
            if proposal.status != expected:
                raise ValueError(
                    f"patch already decided as {proposal.status!r}; "
                    "cannot change decision in v1.6"
                )
            view = self._view(proposal)
            view["merge_decision"] = (proposal.metadata or {}).get("merge_decision")
            view["warning"] = (
                "Merge decision already recorded; main workspace was not modified."
            )
            return view

        now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        merge = PatchMergeDecision(
            decision=decision,  # type: ignore[arg-type]
            reason=reason
            or (
                "human approved merge intent (main tree not modified)"
                if decision == "merge"
                else "human discarded patch"
            ),
            decided_at=now,
            decided_by="human",
            applied_main=False,
        )
        proposal.metadata = {
            **dict(proposal.metadata or {}),
            "merge_decision": merge.model_dump(mode="json"),
            "applied_main": False,
            "apply_main_available": False,
        }
        proposal.status = "merged" if decision == "merge" else "discarded"
        self._repo.upsert(proposal)
        view = self._view(proposal)
        view["merge_decision"] = merge.model_dump(mode="json")
        view["warning"] = (
            "Merge decision recorded only; main workspace was not modified."
        )
        return view

    def list_patches(self, project_id: str) -> list[dict[str, Any]]:
        return [self._view(item) for item in self._repo.list_for_project(project_id)]

    def _view(self, proposal: PatchProposal) -> dict[str, Any]:
        data = proposal.model_dump(mode="json")
        meta = dict(proposal.metadata or {})
        data["can_apply_main"] = False
        data["applied_main"] = bool(meta.get("applied_main"))
        data["can_apply_sandbox"] = proposal.status in {
            "approved",
            "failed_sandbox",
        }
        data["applied_sandbox"] = bool(meta.get("applied_sandbox"))
        data["can_test_sandbox"] = proposal.status == "applied_sandbox"
        data["sandbox_tests_ok"] = meta.get("sandbox_tests_ok")
        data["can_record_evidence"] = proposal.status in {
            "applied_sandbox",
            "evidence_recorded",
        }
        data["can_decide_merge"] = proposal.status == "evidence_recorded"
        data["patch_evidence_id"] = meta.get("patch_evidence_id")
        data["merge_decision"] = meta.get("merge_decision")
        # Back-compat keys used by v1.6.1–1.6.3 tests/CLI.
        data["can_apply"] = False
        data["applied"] = bool(meta.get("applied_sandbox"))
        return data
